### ISSUE TITLE
demo.py error

### ISSUE THREAD

**Issue by no-materials** [laughtervv/DISN#2]
Greetings, thank you for the code release, much appreciated!
I attempted to execute the demo via the command on the README.md file as is, but an error occurs:

```python
Traceback (most recent call last):
  File "demo/demo.py", line 398, in <module>
    create()
  File "demo/demo.py", line 175, in create
    test_one_epoch(sess, ops, batch_data)
  File "demo/demo.py", line 292, in test_one_epoch
    extra_pts = np.zeros((1, SPLIT_SIZE * NUM_SAMPLE_POINTS - TOTAL_POINTS, 3), dtype=np.float32)
ValueError: negative dimensions are not allowed
```

Any ideas on why this occurs? Thanks in advance.

**Comment by Xharlie** [comment]
please reopen the issue if it still has problems after strictly following the README

**Comment by rozentill** [comment]
I met the same problem, it might be caused by python2, since it works on python3. The problem is 

`NUM_SAMPLE_POINTS = int(np.ceil(TOTAL_POINTS / SPLIT_SIZE))`

returns 212183 in python3, but 212182 in python2 because TOTAL_POINTS / SPLIT_SIZE return an integer number 212182 but not floating number 212182.4125  in python2 .
